image: bioconductor/bioconductor_docker:RELEASE_3_17

stages:
  - check
  - deploy

testing:
  artifacts:
    when: on_failure
    paths:
      - testing.log
  stage: check
  script:
    - R -e 'install.packages("devtools")' | tee -a testing.log
    - R -e 'devtools::install()' | tee -a testing.log
    - R -e 'devtools::check()' | tee -a testing.log

pages:
  stage: deploy
  dependencies:
    - testing
  script:
    - R -e 'install.packages("devtools")'
    - R -e 'devtools::install()'
    - R -e 'install.packages("pkgdown")'
    - R -e "pkgdown::build_site()"
    - mkdir -p public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev

