image: bioconductor/bioconductor_docker:RELEASE_3_17

stages:
  - check
  - deploy

testing:
  stage: check
  script:
    - R --no-echo -e 'install.packages("devtools")'
    - R --no-echo -e 'devtools::install(quick = TRUE, quiet = TRUE)'
    - R --no-echo -e 'devtools::check()'

pages:
  stage: deploy
  dependencies:
    - testing
  script:
    - R --no-echo -e 'install.packages("devtools")'
    - R --no-echo -e 'devtools::install(quick = TRUE, quiet = TRUE)'
    - R --no-echo -e 'install.packages("pkgdown")'
    - R --no-echo -e 'pkgdown::build_site()'
    - mkdir -p public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev

