image: rocker/tidyverse

stages:
  - check
  - deploy

testing:
  stage: check
  script:
    - R -e 'install.packages("devtools", verbose = FALSE, quiet = TRUE)'
    - R -e 'devtools::install(quiet=TRUE)'
    - R -e 'devtools::check()'

pages:
  stage: deploy
  dependencies:
    - testing
  script:
    - R -e 'install.packages("devtools")'
    - R -e 'devtools::install()'
    - R -e 'install.packages("pkgdown")'
    - R -e 'pkgdown::build_site()'
    - mkdir -p public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev

