image: bioconductor/bioconductor_docker:RELEASE_3_13

stages:
  - check

building:
  stage: check
  script:
    - R -e 'devtools::install()'
    - R -e 'devtools::check()'

website:
  stage: doc
  branch: dev, main
  script:
    - R -e 'pkgdown::build_site()'


