image: bioconductor/bioconductor_docker:RELEASE_3_19

stages:
  - check
  - deploy

testing:
  artifacts:
    when: on_failure
    paths:
      - testing.log
  stage: check
  script:
    - sudo apt-get update
    - sudo apt-get install -y qpdf
    - Rscript -e 'install.packages("devtools", verbose = FALSE, quiet = TRUE)'
    - BiocManager::install(".", ask=F)
    - Rscript -e 'devtools::check()'

pages:
  stage: deploy
  dependencies:
    - testing
  script:
    - R -e 'install.packages("devtools", verbose = FALSE, quiet = TRUE)'
    - R -e 'devtools::install(quiet=TRUE)'
    - R -e 'install.packages("pkgdown", verbose = FALSE, quiet = TRUE)'
    - R -e 'pkgdown::build_site()'
    - mkdir -p public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev

