image: bioconductor/bioconductor_docker:RELEASE_3_17

stages:
  - check
  - deploy

testing:
  stage: check
  script:
    - R -e 'install.packages("devtools")' > /dev/null
    - R -e 'devtools::install()' > /dev/null
    - R -e 'devtools::check()' > /dev/null

pages:
  stage: deploy
  dependencies:
    - testing
  script:
    - R -e 'install.packages("devtools")' > /dev/null
    - R -e 'devtools::install()' > /dev/null
    - R -e 'install.packages("pkgdown")' > /dev/null
    - R -e "pkgdown::build_site()" > /dev/null
    - mkdir -p public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
  only:
    - master
    - dev

